pipeline:

        build:
                image: docker
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                commands:
                        - docker build -t alan01276/example-webserver . 
        test:
                image: docker
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                commands:
                        - docker run alan01276/example-webserver /test.sh
